// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const SecretSharingSchema = z.object({
  id: z.string().uuid(),
  createdAt: z.date(),
  updatedAt: z.date(),
  secretContent: z.string(),
  read: z.boolean().default(false).nullable().optional(),
  readOnlyOnce: z.boolean().default(false).nullable().optional(),
  pathSlug: z.string(),
  expireAtValue: z.number(),
  expireAtUnit: z.string(),
  isPasswordProtected: z.boolean().default(false).nullable().optional(),
  expireAtDate: z.date(),
  lastReadAt: z.date().nullable().optional(),
  iv: z.string(),
  projectId: z.string()
});

export type TSecretSharing = z.infer<typeof SecretSharingSchema>;
export type TSecretSharingInsert = Omit<z.input<typeof SecretSharingSchema>, TImmutableDBKeys>;
export type TSecretSharingUpdate = Partial<Omit<z.input<typeof SecretSharingSchema>, TImmutableDBKeys>>;
